state_dict = {
    "Florida": {
        "counties": ["Hillsborough,Pasco,Pinellas,Polk"],
        "shelter_date": "2020-03-27",
        "shelter_release_start_date": "2020-05-04",
        "shelter_release_end_date": "2020-06-15",
        "social_distancings": ["false"],
        "social_distancing_end_date": "2020-06-15",
        "quarantine_percents": [0],
        "quarantine_start_date": "2020-08-01",
    },
    "Indiana": {
        "counties": ["St. Joseph"],
        "shelter_date": "2020-03-23",
        "shelter_release_start_date": "2020-05-04",
        "shelter_release_end_date": "2020-06-15",
        "social_distancings": ["false"],
        "social_distancing_end_date": "2020-06-15",
        "quarantine_percents": [0],
        "quarantine_start_date": "2020-08-01",
    },
    "Georgia": {
        "counties": [
            "Cherokee,Clayton,Cobb,DeKalb,Douglas,Fayette,Fulton,Gwinnett,Henry,Rockdale"
        ],
        "shelter_date": "2020-04-03",
        "shelter_release_start_date": "2020-05-04",
        "shelter_release_end_date": "2020-06-15",
        "social_distancings": ["false"],
        "social_distancing_end_date": "2020-06-15",
        "quarantine_percents": [0],
        "quarantine_start_date": "2020-08-01",
    },
    "Illinois": {
        "counties": ["Cook,DeKalb,DuPage,Grundy,Kane,Kankakee,Kendall,McHenry,Will"],
        "shelter_date": "2020-03-21",
        "shelter_release_start_date": "2020-05-04",
        "shelter_release_end_date": "2020-06-15",
        "social_distancings": ["false"],
        "social_distancing_end_date": "2020-06-15",
        "quarantine_percents": [0],
        "quarantine_start_date": "2020-08-01",
    },
    "Ohio": {
        "counties": ["Cuyahoga,Geauga,Lake,Lorain,Medina"],
        "shelter_date": "2020-03-23",
        "shelter_release_start_date": "2020-05-04",
        "shelter_release_end_date": "2020-06-15",
        "social_distancings": ["false"],
        "social_distancing_end_date": "2020-06-15",
        "quarantine_percents": [0],
        "quarantine_start_date": "2020-08-01",
    },
    "Texas": {
        "counties": [
            "Austin,Brazoria,Chambers,Fort Bend,Galveston,Harris,Liberty,Montgomery,Waller"
        ],
        "shelter_date": "2020-04-02",
        "shelter_release_start_date": "2020-05-04",
        "shelter_release_end_date": "2020-06-15",
        "social_distancings": ["false"],
        "social_distancing_end_date": "2020-06-15",
        "quarantine_percents": [0],
        "quarantine_start_date": "2020-08-01",
    },
    "Arizona": {
        "counties": ["Maricopa"],
        "shelter_date": "2020-03-31",
        "shelter_release_start_date": "2020-05-04",
        "shelter_release_end_date": "2020-06-15",
        "social_distancings": ["false"],
        "social_distancing_end_date": "2020-06-15",
        "quarantine_percents": [0],
        "quarantine_start_date": "2020-08-01",
    },
    "Missouri": {
        "counties": [
            "Franklin,Jefferson,Lincoln,St. Charles,St. Louis City,St. Louis,Warren"
        ],
        "shelter_date": "2020-04-06",
        "shelter_release_start_date": "2020-05-04",
        "shelter_release_end_date": "2020-06-15",
        "social_distancings": ["false"],
        "social_distancing_end_date": "2020-06-15",
        "quarantine_percents": [0],
        "quarantine_start_date": "2020-08-01",
    },
    "Kentucky": {
        "counties": [
            "Bullitt,Hardin,Henry,Jefferson,Meade,Nelson,Oldham,Shelby,Spencer,Trimble"
        ],
        "shelter_date": "2020-03-26",
        "shelter_release_start_date": "2020-05-04",
        "shelter_release_end_date": "2020-06-15",
        "social_distancings": ["false"],
        "social_distancing_end_date": "2020-06-15",
        "quarantine_percents": [0],
        "quarantine_start_date": "2020-08-01",
    },
    "Tennessee": {
        "counties": [
            "Cannon,Cheatham,Davidson,Dickson,Hickman,Macon,Maury,Robertson,Rutherford,Smith,Sumner,Trousdale,Williamson,Wilson"
        ],
        "shelter_date": "2020-03-31",
        "shelter_release_start_date": "2020-05-04",
        "shelter_release_end_date": "2020-06-15",
        "social_distancings": ["false"],
        "social_distancing_end_date": "2020-06-15",
        "quarantine_percents": [0],
        "quarantine_start_date": "2020-08-01",
    },
    "Iowa": {
        "counties": ["Polk"],
        "shelter_date": "2020-03-17",
        "shelter_release_start_date": "2020-05-04",
        "shelter_release_end_date": "2020-06-15",
        "social_distancings": ["false"],
        "social_distancing_end_date": "2020-06-15",
        "quarantine_percents": [0],
        "quarantine_start_date": "2020-08-01",
    },
    "California": {
        "counties": ["Los Angeles"],
        "shelter_date": "2020-03-19",
        "shelter_release_start_date": "2020-05-04",
        "shelter_release_end_date": "2020-06-15",
        "social_distancings": ["false"],
        "social_distancing_end_date": "2020-06-15",
        "quarantine_percents": [0],
        "quarantine_start_date": "2020-08-01",
    },
    "Alabama": {
        "counties": ["Bibb,Blount,Chilton,Jefferson,St. Clair,Shelby,Walker"],
        "shelter_date": "2020-04-04",
        "shelter_release_start_date": "2020-05-04",
        "shelter_release_end_date": "2020-06-15",
        "social_distancings": ["false"],
        "social_distancing_end_date": "2020-06-15",
        "quarantine_percents": [0],
        "quarantine_start_date": "2020-08-01",
    },
    "Michigan": {
        "counties": ["Lapeer,Livingston,Macomb,Oakland,St. Clair,Wayne"],
        "shelter_date": "2020-03-24",
        "shelter_release_start_date": "2020-05-04",
        "shelter_release_end_date": "2020-06-15",
        "social_distancings": ["false"],
        "social_distancing_end_date": "2020-06-15",
        "quarantine_percents": [0],
        "quarantine_start_date": "2020-08-01",
    },
    "Pennsylvania": {
        "counties": ["Bucks,Chester,Delaware,Montgomery,Philadelphia"],
        "shelter_date": "2020-04-01",
        "shelter_release_start_date": "2020-05-04",
        "shelter_release_end_date": "2020-06-15",
        "social_distancings": ["false"],
        "social_distancing_end_date": "2020-06-15",
        "quarantine_percents": [0],
        "quarantine_start_date": "2020-08-01",
    },
    "Minnesota": {
        "counties": ["Hennepin"],
        "shelter_date": "2020-03-27",
        "shelter_release_start_date": "2020-05-04",
        "shelter_release_end_date": "2020-06-15",
        "social_distancings": ["false"],
        "social_distancing_end_date": "2020-06-15",
        "quarantine_percents": [0],
        "quarantine_start_date": "2020-08-01",
    },
    "Wisconsin": {
        "counties": ["Dane"],
        "shelter_date": "2020-03-25",
        "shelter_release_start_date": "2020-05-04",
        "shelter_release_end_date": "2020-06-15",
        "social_distancings": ["false"],
        "social_distancing_end_date": "2020-06-15",
        "quarantine_percents": [0],
        "quarantine_start_date": "2020-08-01",
    },
    "Mississippi": {
        "counties": ["Hinds"],
        "shelter_date": "2020-04-03",
        "shelter_release_start_date": "2020-05-04",
        "shelter_release_end_date": "2020-06-15",
        "social_distancings": ["false"],
        "social_distancing_end_date": "2020-06-15",
        "quarantine_percents": [0],
        "quarantine_start_date": "2020-08-01",
    },
    "Louisiana": {
        "counties": ["Baton Rouge"],
        "shelter_date": "2020-03-23",
        "shelter_release_start_date": "2020-05-04",
        "shelter_release_end_date": "2020-06-15",
        "social_distancings": ["false"],
        "social_distancing_end_date": "2020-06-15",
        "quarantine_percents": [0],
        "quarantine_start_date": "2020-08-01",
    },
}